//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigSisterServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BigSisterServiceReference.IBigSisterService")]
    public interface IBigSisterService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigSisterService/CalculateSpaceShipPrice", ReplyAction="http://tempuri.org/IBigSisterService/CalculateSpaceShipPriceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BigSister.SpaceShipCargo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BigSister.SpaceShipFamily))]
        int CalculateSpaceShipPrice(BigSister.SpaceShip spaceShip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigSisterService/CalculateSpaceShipPrice", ReplyAction="http://tempuri.org/IBigSisterService/CalculateSpaceShipPriceResponse")]
        System.Threading.Tasks.Task<int> CalculateSpaceShipPriceAsync(BigSister.SpaceShip spaceShip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IBigSisterServiceChannel : BigSisterServiceReference.IBigSisterService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class BigSisterServiceClient : System.ServiceModel.ClientBase<BigSisterServiceReference.IBigSisterService>, BigSisterServiceReference.IBigSisterService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BigSisterServiceClient() : 
                base(BigSisterServiceClient.GetDefaultBinding(), BigSisterServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBigSisterService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BigSisterServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BigSisterServiceClient.GetBindingForEndpoint(endpointConfiguration), BigSisterServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BigSisterServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BigSisterServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BigSisterServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BigSisterServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BigSisterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int CalculateSpaceShipPrice(BigSister.SpaceShip spaceShip)
        {
            return base.Channel.CalculateSpaceShipPrice(spaceShip);
        }
        
        public System.Threading.Tasks.Task<int> CalculateSpaceShipPriceAsync(BigSister.SpaceShip spaceShip)
        {
            return base.Channel.CalculateSpaceShipPriceAsync(spaceShip);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBigSisterService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBigSisterService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/BigSister/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BigSisterServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBigSisterService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BigSisterServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBigSisterService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBigSisterService,
        }
    }
}
